export const products = [
  {
    id: 1,
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.00",
    originalPrice: "Rp 3.500.00",
    discount: "30%",
    image: "/shop/image 1.png",
    about: "Our Syltherine Chair is a modern take on the classic cafe chair. Crafted with a sturdy Kikar Wood Frame and featuring Master Molty Foam, it ensures both durability and luxury. Its gently slanted backrest and flared armrests add a touch of sophistication to any space.",
    Sku: "SS001",
    Category: "Table"
  },
  {
    id: 2,
    name: "Leviosa",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    image: "/shop/image 2.png",
    about: "Our Leviosa Chair is a modern take on the classic cafe chair. Crafted with a sturdy Kikar Wood Frame and featuring Master Molty Foam, it ensures both durability and luxury. Its gently slanted backrest and flared armrests add a touch of sophistication to any space.",
    Sku: "SS002", 
    Category: "Chair"
  },
  {
    id: 3,
    name: "Lolito",
    description: "Luxury big sofa",
    price: "Rp 7.000.00",
    originalPrice: "Rp 14.000.00",
    discount: "50%",
    image: "/shop/image 3.png",
  },
  {
    id: 4,
    name: "Respira",
    description: "Outdoor bar table and stool",
    price: "Rp 500.000",
    new: true,
    image: "/shop/image 4.png"
  },
  {
    id: 5,
    name: "Grifo",
    description: "Night lamp",
    price: "Rp 1.500.000",
    image: "/shop/image 9.png"
  },
  {
    id: 6,
    name: "Muggo",
    description: "Small mug",
    price: "Rp 150.000",
    new: true,
    image: "/shop/muggo.png"
  },
  {
    id: 7,
    name: "Pingky",
    description: "Cute bed set",
    price: "Rp 7.000.00",
    originalPrice: "Rp 14.000.00",
    discount: "50%",
    image: "/shop/pingky.png",
  },
  {
    id: 8,
    name: "Potty",
    description: "Minimalist flower pot",
    price: "Rp 500.000",
    new: true,
    image: "/shop/potty.png",
  },
  {
    id: 9,
    name: "Syltherine",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    originalPrice: "Rp 3.500.000",
    discount: "30%",
    image: "/shop/image 1.png",
    about: "Our Syltherine Chair is a modern take on the classic cafe chair. Crafted with a sturdy Kikar Wood Frame and featuring Master Molty Foam, it ensures both durability and luxury. Its gently slanted backrest and flared armrests add a touch of sophistication to any space.",
    Sku: "SS009",
    Category: "Table",
  },
  {
    id: 10,
    name: "Leviosa",
    description: "Stylish cafe chair",
    price: "Rp 2.500.000",
    image: "/shop/image 2.png",
  },
  {
    id: 11,
    name: "Michon Sofa",
    description: "Single Seater Luxury sofa",
    about:"Our Michon Sofa Chair exudes chic modernity and unparalleled comfort. Crafted with a sturdy Kikar Wood Frame and featuring Master Molty Foam, it ensures both durability and luxury. Its gently slanted tufted backrest and flared armrests add a touch of sophistication to any space.",
    price: "Rp 7.000.000",
    originalPrice: "Rp 14.000.000",
    discount: "50%",
    image: "/shop/singlesofa.png",
  },
  {
    id: 12,
    name: "Respira",
    description: "Outdoor bar table and stool",
    price: "Rp 500.000",
    new: true,
    image: "/shop/image 4.png"
  },
  {
    id: 13,
    name: "Grifo",
    description: "Night lamp",
    price: "Rp 1.500.000",
    image: "/shop/image 6.png"
  },
  {
    id: 14,
    name: "Muggo",
    description: "Small mug",
    price: "Rp 150.000",
    new: true,
    image: "/shop/image 7.png"
  },
  {
    id: 15,
    name: "Pingky",
    description: "Cute bed set",
    price: "Rp 7.000.000",
    originalPrice: "Rp 14.000.000",
    discount: "50%",
    image: "/shop/image 9.png",
  },
  {
    id: 16,
    name: "Potty",
    description: "Minimalist flower pot",
    price: "Rp 500.000",
    new: true,
    image: "/shop/image5.png",
  },
];